name: Generate README
on:
  workflow_dispatch:

jobs:
  Generate-README:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo ${{ github.workspace }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}