name: Generate README
on:
  workflow_dispatch:

jobs:
  Generate-README:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo ${{ github.workspace }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install flake8 pytest
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Python
        run: |
          python .github/workflows/generate_readme.py
